// Generated by gencpp from file robot_move_server/RobotMoveServerOrder.msg
// DO NOT EDIT!


#ifndef ROBOT_MOVE_SERVER_MESSAGE_ROBOTMOVESERVERORDER_H
#define ROBOT_MOVE_SERVER_MESSAGE_ROBOTMOVESERVERORDER_H

#include <ros/service_traits.h>


#include <robot_move_server/RobotMoveServerOrderRequest.h>
#include <robot_move_server/RobotMoveServerOrderResponse.h>


namespace robot_move_server
{

struct RobotMoveServerOrder
{

typedef RobotMoveServerOrderRequest Request;
typedef RobotMoveServerOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotMoveServerOrder
} // namespace robot_move_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_move_server::RobotMoveServerOrder > {
  static const char* value()
  {
    return "8836a8af838d74e0e72cd61a7e1e78f6";
  }

  static const char* value(const ::robot_move_server::RobotMoveServerOrder&) { return value(); }
};

template<>
struct DataType< ::robot_move_server::RobotMoveServerOrder > {
  static const char* value()
  {
    return "robot_move_server/RobotMoveServerOrder";
  }

  static const char* value(const ::robot_move_server::RobotMoveServerOrder&) { return value(); }
};


// service_traits::MD5Sum< ::robot_move_server::RobotMoveServerOrderRequest> should match
// service_traits::MD5Sum< ::robot_move_server::RobotMoveServerOrder >
template<>
struct MD5Sum< ::robot_move_server::RobotMoveServerOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_move_server::RobotMoveServerOrder >::value();
  }
  static const char* value(const ::robot_move_server::RobotMoveServerOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_move_server::RobotMoveServerOrderRequest> should match
// service_traits::DataType< ::robot_move_server::RobotMoveServerOrder >
template<>
struct DataType< ::robot_move_server::RobotMoveServerOrderRequest>
{
  static const char* value()
  {
    return DataType< ::robot_move_server::RobotMoveServerOrder >::value();
  }
  static const char* value(const ::robot_move_server::RobotMoveServerOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_move_server::RobotMoveServerOrderResponse> should match
// service_traits::MD5Sum< ::robot_move_server::RobotMoveServerOrder >
template<>
struct MD5Sum< ::robot_move_server::RobotMoveServerOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_move_server::RobotMoveServerOrder >::value();
  }
  static const char* value(const ::robot_move_server::RobotMoveServerOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_move_server::RobotMoveServerOrderResponse> should match
// service_traits::DataType< ::robot_move_server::RobotMoveServerOrder >
template<>
struct DataType< ::robot_move_server::RobotMoveServerOrderResponse>
{
  static const char* value()
  {
    return DataType< ::robot_move_server::RobotMoveServerOrder >::value();
  }
  static const char* value(const ::robot_move_server::RobotMoveServerOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MOVE_SERVER_MESSAGE_ROBOTMOVESERVERORDER_H
