// Generated by gencpp from file robot_move_server/RobotMoveServerOrderResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MOVE_SERVER_MESSAGE_ROBOTMOVESERVERORDERRESPONSE_H
#define ROBOT_MOVE_SERVER_MESSAGE_ROBOTMOVESERVERORDERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_move_server
{
template <class ContainerAllocator>
struct RobotMoveServerOrderResponse_
{
  typedef RobotMoveServerOrderResponse_<ContainerAllocator> Type;

  RobotMoveServerOrderResponse_()
    : result()  {
    }
  RobotMoveServerOrderResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotMoveServerOrderResponse_

typedef ::robot_move_server::RobotMoveServerOrderResponse_<std::allocator<void> > RobotMoveServerOrderResponse;

typedef boost::shared_ptr< ::robot_move_server::RobotMoveServerOrderResponse > RobotMoveServerOrderResponsePtr;
typedef boost::shared_ptr< ::robot_move_server::RobotMoveServerOrderResponse const> RobotMoveServerOrderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator1> & lhs, const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator1> & lhs, const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_move_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_move_server/RobotMoveServerOrderResponse";
  }

  static const char* value(const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotMoveServerOrderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_move_server::RobotMoveServerOrderResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MOVE_SERVER_MESSAGE_ROBOTMOVESERVERORDERRESPONSE_H
