(cl:defpackage robot_move_server-srv
  (:use )
  (:export
   "ROBOTMOVESERVERORDER"
   "<ROBOTMOVESERVERORDER-REQUEST>"
   "ROBOTMOVESERVERORDER-REQUEST"
   "<ROBOTMOVESERVERORDER-RESPONSE>"
   "ROBOTMOVESERVERORDER-RESPONSE"
  ))

